### ISSUE TITLE
ImportError: No module named matplotlib.numerix

### ISSUE THREAD

**Issue by Chaoba** [dmnfarrell/tkintertable#26]
I runed Freeze.py and it got an error as follows:

```
Traceback (most recent call last):
  File "D:/pythonTable/tkintertable-master/Application/freeze.py", line 28, in <module>
    f()    # runs the freezing process

  File "D:\Program Files\anaconda\lib\site-packages\bbfreeze\freezer.py", line 593, in __call__
    if not self._handleRecipes():

  File "D:\Program Files\anaconda\lib\site-packages\bbfreeze\freezer.py", line 483, in _handleRecipes
    if x(self.mf):

  File "D:\Program Files\anaconda\lib\site-packages\bbfreeze\recipes.py", line 236, in recipe_matplotlib
    mf.import_hook("matplotlib.numerix.random_array", m)

  File "D:\Program Files\anaconda\lib\site-packages\bbfreeze\modulegraph\modulegraph.py", line 257, in import_hook
    m = self.load_tail(q, tail)

  File "D:\Program Files\anaconda\lib\site-packages\bbfreeze\modulegraph\modulegraph.py", line 341, in load_tail
    raise ImportError, "No module named " + mname

ImportError: No module named matplotlib.numerix
```

**Comment by dmnfarrell** [comment]
If you are using freeze.py I assume it's because you want to make an exe for windows?

**Comment by Chaoba** [comment]
@dmnfarrell You are right, and I have googled this issue still not fix it.

**Comment by dmnfarrell** [comment]
That freeze script was last used a long time ago and is really legacy code now. It probably doesn't work because of your version of python and/or matplotlib. I am not sure why you would need to be turn this into an exe for windows? If you want a table app then I'd suggest you use dataexplore which is based on pandastable that replaces this package. http://dmnfarrell.github.io/pandastable/

**Comment by Chaoba** [comment]
I just want to learn python UI through you project. It is really helpful. Thanks a lot.
