### ISSUE TITLE
incorrect installation or smth

### ISSUE THREAD

**Issue by arpanetus** [dmnfarrell/tkintertable#30]
```>>> import tkintertable.Tables
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Python36-32\lib\site-packages\tkintertable\__init__.py", line 24, in <module>
    from Tables import *
ModuleNotFoundError: No module named 'Tables'

**Comment by dmnfarrell** [comment]
You should use python 2 and it should work.
