### ISSUE TITLE
Tkintertable Key word ‘link’

### ISSUE THREAD

**Issue by SchuppiM** [dmnfarrell/tkintertable#57]
Tkintertable can’t digest the key word ‘linked’.

I’m loading a tkintertable with data from an Access DB.
In there, there is a text containing the word ‘linked’.
Loading it to tkintertable is not causing an error, but then scrolling down in the table I get this:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tkintertable-1.3.2-py3.7.egg\tkintertable\Tables.py", line 154, in mouse_wheel
    self.redrawVisible()
  File "C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tkintertable-1.3.2-py3.7.egg\tkintertable\Tables.py", line 352, in redrawVisible
    self.drawText(row, col, text, fgcolor, align)
  File "C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tkintertable-1.3.2-py3.7.egg\tkintertable\Tables.py", line 1722, in drawText
    linktext=celltxt['text']
TypeError: string indices must be integers

Here the statement the cell is populated with:
self.ReportTab3Table.model.setValueAt(str(self.sWOTitle), self.iI, 2)

I played around with it, it is what ever word is starting with ‘link’.
Any idea how to get this solved?

**Comment by dmnfarrell** [comment]
It's because it checks for this as a keyword to support hyperlinks. It should be fixed now.

**Comment by SchuppiM** [comment]
@dmnfarrell 
Means I Need to download a new Version?
Please share the link where I can get it.
Thx for your quick support!

**Comment by dmnfarrell** [comment]
How did you install it.

**Comment by SchuppiM** [comment]
@dmnfarrell
Downloaded it from a link I found.
Then I run 
python setup.py install

**Comment by dmnfarrell** [comment]
download from here: https://github.com/dmnfarrell/tkintertable/archive/master.zip
and install again

**Comment by SchuppiM** [comment]
@dmnfarrell
Thx so much!
