### ISSUE TITLE
Install / first use problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dmnfarrell/tkintertable#7]
```
What steps will reproduce the problem?
1. Just use the first 2 import statements
2.
3.

What is the expected output? What do you see instead?
Expect:   Goodness
Actual:
Traceback (most recent call last):
  File "C:\Python32\tbvpython\tkintertable_test1.py", line 5, in <module>
    from tkintertable.Tables import TableCanvas
  File "C:\Python32\lib\site-packages\tkintertable-1.1.2-py3.2-win32.egg\tkintertable\Tables.py", line 560
    print 'found in',row,col
                   ^
SyntaxError: invalid syntax


What version of the product are you using? On what operating system?  1.1.2 
against Python32 on windows XP machine


Please provide any additional information below.
tkinter works with no problem


```

Original issue reported on code.google.com by `Ted.Vojn...@gmail.com` on 23 Oct 2013 at 12:45

**Comment by dmnfarrell** [comment]
python 3 not compatible
